// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgdQZgqH3-wvjqEVQddh_ym8xGGCqaZPo',
    appId: '1:88076839712:web:956b5e5c1558866b510545',
    messagingSenderId: '88076839712',
    projectId: 'gantav-ai',
    authDomain: 'gantav-ai.firebaseapp.com',
    storageBucket: 'gantav-ai.firebasestorage.app',
    measurementId: 'G-BLDGPL87CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8t7zu_AiCD8XYHjBOaMIgeECjOit6Hgw',
    appId: '1:88076839712:android:954f9e961732609b510545',
    messagingSenderId: '88076839712',
    projectId: 'gantav-ai',
    storageBucket: 'gantav-ai.firebasestorage.app',
  );
}
